# Generated by Django 2.2.3 on 2019-07-06 17:14

from django.db import migrations

from utils.generate_poligons import PoligonDataGenerator


def create_poligons(*args, **kwargs):
    PoligonDataGenerator.generate_poligons()


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_poligons)
    ]
