# Generated by Django 2.2.3 on 2020-03-21 18:25
import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_points(*args, **kwargs):
    fixture_path = os.path.join(settings.BASE_DIR, 'geo_data', 'fixtures', 'initial_data.json')
    call_command('loaddata', fixture_path)


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_points)
    ]
