# Generated by Django 2.2.3 on 2019-07-06 17:14

from django.db import migrations

from utils.generate_polygons import PolygonDataGenerator


def create_polygons(*args, **kwargs):
    PolygonDataGenerator.generate_polygons()


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_polygons)
    ]
