# Generated by Django 3.1.6 on 2021-02-12 10:17

import os

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


def load_points(*args, **kwargs):
    """Загрузка начальных данных."""
    fixture_files = [
        'initial_settings.json',
        'initial_yaroslavl.json',
        'initial_kazan.json',
    ]
    for file in fixture_files:
        fixture_path = os.path.join(
            settings.BASE_DIR,
            'geo_data',
            'fixtures',
            file
        )
        call_command('loaddata', fixture_path)


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_points)
    ]
