# Generated by Django 2.2.3 on 2019-07-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0002_auto_20190706_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('title', models.CharField(max_length=256)),
                ('kind', models.CharField(choices=[('infant_school', 'infant_school'), ('school', 'school'), ('bus_stop', 'bus_stop'), ('hospital', 'hospital'), ('culture', 'culture'), ('sports_ground', 'sports_ground')], max_length=25)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_data.Polygon')),
            ],
        ),
    ]
