# Generated by Django 3.1.8 on 2021-05-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0002_auto_20210212_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('rating', models.DecimalField(decimal_places=1, default=10.0, max_digits=3, verbose_name='Рейтинг')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='radius',
        ),
        migrations.CreateModel(
            name='CategoriesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(verbose_name='Радиус действия категории в метрах')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_data.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_data.city')),
            ],
        ),
    ]
