# Generated by Django 3.1.8 on 2021-05-02 20:08

from django.db import migrations


def create_city_and_category_settings(apps, schema_editor):
    City = apps.get_model('geo_data', 'City')
    Category = apps.get_model('geo_data', 'Category')
    CategoriesSettings = apps.get_model('geo_data', 'CategoriesSettings')
    city, _ = City.objects.get_or_create(
        name='Ярославль',
        longitude=39.893804,
        latitude=57.626559,
    )
    for category in Category.objects.all():
        CategoriesSettings.objects.create(
            category=category,
            city=city,
            radius=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_auto_20210502_2127'),
    ]

    operations = [
        migrations.RunPython(create_city_and_category_settings)
    ]
