# Generated by Django 2.2.3 on 2019-07-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='kind',
            field=models.CharField(choices=[('infant_school', 'infant_school'), ('school', 'school'), ('bus_station', 'bus_station'), ('hospital', 'hospital'), ('culture', 'culture'), ('sports_ground', 'sports_ground'), ('post_office', 'post_office'), ('waste_points', 'waste_points')], max_length=25),
        ),
        migrations.AlterField(
            model_name='point',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='geo_data.Polygon'),
        ),
    ]
