# Generated by Django 3.0.4 on 2020-06-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_auto_20200613_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='debug',
        ),
        migrations.AddField(
            model_name='geoobject',
            name='debug',
            field=models.BooleanField(
                default=False,
                verbose_name='Отладочный объект'
            ),
        ),
    ]
