# Generated by Django 2.2.3 on 2019-07-07 07:17

from django.db import migrations

from geo_data.tools.calculate_threshold_values import ThresholdValuesCalculator


def calc_values(*args, **kwargs):
    ThresholdValuesCalculator.calculate_max_values_and_parts()


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0005_value'),
    ]

    operations = [
        migrations.RunPython(calc_values)
    ]
