# Generated by Django 2.2.3 on 2019-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0006_auto_20190707_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('radius', models.IntegerField(blank=True, verbose_name='Радиус действия категории в метрах')),
                ('power', models.BooleanField(default=True, verbose_name='Степень влияния')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
        ),
    ]
