version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.9
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links: 
      - db
    
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_USER=rebus
    - POSTGRES_PASSWORD=rebus
    - POSTGRES_DB=rebus_db
